# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7239ac5d12ec739584474aa0fcaca40d8f57c1e1281eb459234c2397b22bea61ac28828f12d8f1e2632ccd7cb785f3a6464def160e7f9f537cd7f5b9110d4dd3

test:
  secret_key_base: dd4cf986ccadf6d1d1d789e915f298cd868409639f901d421d8db412a8a7716d322d972614d30e7f4bc49d802fc96ef9d33ded277bb18be701b879a428c67b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
